#!/usr/bin/env python3
"""Export golden reference vectors for the C++ port to be validated against.

The Python models in this package are the reference implementation; the C++
blocks in ``audio-engine/`` are a port of them. This script freezes a render
from each Python model into a fixture that ``audio-engine``'s
``test_python_parity.cpp`` replays through the C++ block, so "the C++ sounds
the same" is an assertion in CI rather than a claim.

    python tools/export_golden.py ../audio-engine/tests/golden/pedal_parity.json

**The input is pre-quantized to float32** before Python processes it. The C++
engine's buffers are ``float`` (see ``effect_block.hpp``), so quantizing first
means both languages start from bit-identical input values and the only
remaining difference is intermediate precision -- C++ keeps its DSP state in
``double`` and rounds once on the way out, which lands within ~1e-7.

The oversampler's FIR taps are exported too. C++ recomputes them from the same
windowed-sinc definition rather than hardcoding 65 magic numbers, and the
parity test checks that reconstruction against these -- so a divergence in the
filter design shows up as its own failure rather than as a mysteriously wrong
waveform.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from pedals import BigMuff, NoiseGate, TubeScreamer  # noqa: E402
from pedals.dsp import Oversampler  # noqa: E402

SAMPLE_RATE = 48000.0
NUM_SAMPLES = 4096
BLOCK_SIZE = 64
DIGITS = 12


def test_signal() -> np.ndarray:
    """A short take exercising transients, sustain and a noise floor.

    Deliberately includes a quiet passage at each end so the noise gate has
    something to close on, and a hard onset so the attack path is covered.
    """
    rng = np.random.default_rng(20240917)
    t = np.arange(NUM_SAMPLES) / SAMPLE_RATE
    signal = np.zeros(NUM_SAMPLES)

    onset = int(0.01 * SAMPLE_RATE)
    decay = np.exp(-(t[: NUM_SAMPLES - onset]) * 18.0)
    tone = t[: NUM_SAMPLES - onset]
    signal[onset:] = 0.45 * decay * (
        np.sin(2.0 * np.pi * 146.8 * tone)
        + 0.6 * np.sin(2.0 * np.pi * 293.7 * tone)
        + 0.25 * np.sin(2.0 * np.pi * 587.3 * tone)
    )
    signal += 0.0012 * rng.standard_normal(NUM_SAMPLES)

    # Quantize to float32: the C++ side's buffers are float, so both languages
    # must start from exactly the same values.
    return np.float32(signal).astype(np.float64)


def render(pedal, x: np.ndarray) -> np.ndarray:
    """Render in blocks, the same way the C++ engine will."""
    return np.concatenate(
        [pedal.process(x[i:i + BLOCK_SIZE]) for i in range(0, len(x), BLOCK_SIZE)]
    )


def build_cases(x: np.ndarray) -> list[dict]:
    cases = []

    big_muff = BigMuff(SAMPLE_RATE)
    muff_params = {"sustain": 0.72, "tone": 0.38, "volume": 0.64, "pad_15db": False}
    big_muff.set_params(**muff_params)
    cases.append({"type": BigMuff.TYPE, "params": muff_params, "output": render(big_muff, x)})

    padded = BigMuff(SAMPLE_RATE)
    padded_params = {"sustain": 0.9, "tone": 0.5, "volume": 1.0, "pad_15db": True}
    padded.set_params(**padded_params)
    cases.append({"type": BigMuff.TYPE, "params": padded_params, "output": render(padded, x)})

    screamer = TubeScreamer(SAMPLE_RATE)
    ts_params = {"drive": 0.66, "tone": 0.55, "level": 0.7}
    screamer.set_params(**ts_params)
    cases.append({"type": TubeScreamer.TYPE, "params": ts_params, "output": render(screamer, x)})

    gate = NoiseGate(SAMPLE_RATE)
    # Timings short enough that the gate fully opens and closes again inside
    # the fixture's 85 ms, so the parity test covers every branch of the state
    # machine rather than just the open one.
    gate_params = {
        "threshold_db": -38.0, "range_db": -55.0, "attack_ms": 1.5,
        "hold_ms": 8.0, "release_ms": 25.0, "hysteresis_db": 6.0,
    }
    gate.set_params(**gate_params)
    cases.append({"type": NoiseGate.TYPE, "params": gate_params, "output": render(gate, x)})

    return cases


def rounded(values: np.ndarray) -> list[float]:
    """Trim to a precision comfortably finer than the parity tolerance."""
    return [float(f"%.{DIGITS}g" % v) for v in values]


def main(argv: list[str] | None = None) -> int:
    args = argv if argv is not None else sys.argv[1:]
    if len(args) != 1:
        print(__doc__, file=sys.stderr)
        return 2
    destination = Path(args[0])

    x = test_signal()
    cases = build_cases(x)

    document = {
        "_comment": (
            "Generated by vst-python/tools/export_golden.py -- do not edit by hand. "
            "Regenerate after any change to the Python models, and expect the C++ "
            "parity test to fail until the corresponding C++ block is updated to match."
        ),
        "sample_rate": SAMPLE_RATE,
        "block_size": BLOCK_SIZE,
        "oversample": 4,
        "fir_taps": rounded(Oversampler(factor=4)._fir),
        "input": rounded(x),
        "cases": [
            {"type": c["type"], "params": c["params"], "output": rounded(c["output"])}
            for c in cases
        ],
    }

    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(json.dumps(document, indent=1))
    size_kb = destination.stat().st_size / 1024.0
    print(
        f"wrote {destination} ({size_kb:.0f} KB): "
        f"{len(cases)} cases x {NUM_SAMPLES} samples @ {SAMPLE_RATE:.0f} Hz"
    )
    for case in cases:
        peak = float(np.max(np.abs(case["output"])))
        print(f"  {case['type']:14s} peak {peak:.4f}  {case['params']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
